### ISSUE TITLE
0.1.0 To Do Tasks

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#1]
1. Connection
    - Connection to Live Database
        - [x] `Database`: abstract interface of a database
        - [x] `Connection`: a live connection able to execute SQL statements
        - [x] `ExecutionResult`: execution result of non select query
        - [x] #83
    - Backend support
        - [x] SQLx MySql
        - [x] SQLx Postgres (#19)
        - [x] #33
    - Mock Connection
        - [x] Provide a mock database API for unit testing

1. ORM Core
    - Components
      - [x] `Entity`: encapsulates all the necessary specification of the corresponding database table
        - [x] `Column`: column name
        - [x] `PrimaryKey`: primary key name
        - [x] `Relation`: definition of relation between tables
      - [x] `Model`: struct to store the data of a database row
    - Query Result
      - [x] serialize to serde_json::Value (#4)
    - Entity Generator
      - [x] Given a table schema (from [sea-schema](https://github.com/SeaQL/sea-schema)), generate `Entity` file as Rust code (#11)

1. Select from Table
    - [x] Execute the `SelectStatment` and return one or many models
    - [x] Select into custom (ad hoc) models
    - [x] where (filter and condition)
    - [x] order_by
    - [x] Paginate selection result
      - [x] Stream sync item (#5)
              i.e. into `impl Stream<Item = Result<_, _>>`
      - [x] Test cases for Paginator implemented with mock connection
    - [x] Relations: one to one and one to many
    - [x] Relation: many to many via junction table

1. Insert into Table
    - [x] Insert one model into database
    - [x] Insert multiple models as a single query

1. Update from Table
    - [x] Update a whole model to a row
    - [x] `ActiveModel`: wrap `Model` and indicates which fields are modified, and only update respective columns
    - [x] `save` semantics: insert if model is new, otherwise update
    - [x] Update many using filters

1. Delete from Table
    - [x] Delete one model
    - [x] Delete many models using filters (similar to select)

1. Utility (#24)
    - [x] `Discovery`: `generate` command to generate entities from existing database

1. Test suite
    - [x] `bakery`: a database schema for demonstration (#32)
    - [x] end-to-end test suite (#41)
    - [x] runnable on CI (GitHub Action) for Sqlite (#25)
