### ISSUE TITLE
0.2.0 To Write Docs

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#115]
## Content

1. [x] PrimaryKeyTrait::ValueType #103
1. [x] Linked API #89
1. [x] Entity to TableCreateStatement #59
1. [x] SelectorRaw API #73
1. [x] Writing tests SeaQL/seaql.github.io#1
1. [x] Debug Log #114
1. [x] Support sea-orm-cli --verbose #153
1. [x] Codegen for compact Entity format #138
1. [x] New Entity format #105
1. [x] EntityModel ignore columns #159
1. [x] Select from Statement #167

**Comment by tyt2y3** [comment]
Seems like all issues are merged now!
