### ISSUE TITLE
Upgrade SQLx dependency to 0.6.x

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-orm#808]
## Motivation

Upgrading SQLx dependency as well as the downstream dependencies such as `time`, `uuid`, `bigdecimal`, etc.

## Tasks

- [x] Upgrade to SQLx 0.6.x
- [x] Upgrade to time 0.3.x
    - https://github.com/SeaQL/sea-orm/issues/788
- [x] Upgrade to uuid 1.x
    - https://github.com/SeaQL/sea-orm/issues/689

## Additional Information

Potential Breaking Changes
* https://github.com/launchbadge/sqlx/issues/1618  
  SQLite `chrono::DateTime<FixedOffset>` timezone fix
    * `DateTime<FixedOffset>` will be stored in SQLite with the correct timezone instead of always in UTC.
      This was flagged as a "potentially breaking change" since it changes how dates are sent to SQLite.
* https://github.com/launchbadge/sqlx/issues/1901
  Pool fixes and breaking changes
    * Renamed `PoolOptions::connect_timeout` to `acquire_timeout` for clarity.

**Comment by tyt2y3** [comment]
Is there a PR for this yet?

**Comment by billy1624** [comment]
No active PR at the moment :P

**Comment by Sytten** [comment]
Yeah agreed, needs an update to time. I am wondering if chrono support should be just removed, its basically deprecated.
It's a bit annoying that when using `sqlx-postgres`, chrono gets added automatically and also the CLI defaults to chrono without a flag for time.

**Comment by tyt2y3** [comment]
Regarding unwanted dependencies, I think we can take advantage of `?` dependency and solve that

**Comment by tyt2y3** [comment]
sea-query and sea-schema is already upgraded and released to sqlx 0.6
@billy1624 sea-orm side can assign to you?

**Comment by tyt2y3** [comment]
> I am wondering if chrono support should be just removed, its basically deprecated

I also don't oppose to change the default in SeaORM if a lib is deprecated. However is there a source for this information?

**Comment by Sytten** [comment]
Well its not dead but no release in two years and unpatched vulnerability. The current master is very different from the current release. You can keep it with the ? Thats true.

**Comment by ikrivosheev** [comment]
> sea-query and sea-schema is already upgraded to sqlx 0.6 and released
> @billy1624 sea-orm side can assign to you?
> Or you'd need help from Ivan?

Did you mean me?

**Comment by tyt2y3** [comment]
> > sea-query and sea-schema is already upgraded to sqlx 0.6 and released
> > @billy1624 sea-orm side can assign to you?
> > Or you'd need help from Ivan?
> 
> @tyt2y3 did you mean me?

Haha yes

**Comment by billy1624** [comment]
> Yeah agreed, needs an update to time. I am wondering if chrono support should be just removed, its basically deprecated. It's a bit annoying that when using `sqlx-postgres`, chrono gets added automatically and also the CLI defaults to chrono without a flag for time.

Hey @Sytten, do you mean generate entity with datetime field defined with `time` types?
- https://github.com/SeaQL/sea-orm/pull/724

**Comment by billy1624** [comment]
> sea-query and sea-schema is already upgraded to sqlx 0.6 and released @billy1624 sea-orm side can assign to you? Or you'd need help from Ivan?

Yes, please! I've created a PR for this but it's still WIP. Please check https://github.com/SeaQL/sea-orm/pull/834 and see if you have anything to add. Just feel free to push commits to the branch.

I'll get back and work on it tomorrow. Thanks! :D

**Comment by billy1624** [comment]
Hey everyone, https://github.com/SeaQL/sea-orm/pull/834 is ready for review! :)
